// Seed dataset for MusicRoots.
// Edges read "artist  <-  influenced_by" (A draws influence from B).
// Every edge carries at least one confirming source.

export const artists = [
  // --- Delta blues roots ---
  { slug: "charley-patton", name: "Charley Patton", type: "artist", country: "США",
    active_from: 1910, active_to: 1934, tags: ["delta-blues"],
    bio: "Один из основателей дельта-блюза, «отец Delta Blues», учитель целого поколения блюзменов Миссисипи." },
  { slug: "son-house", name: "Son House", type: "artist", country: "США",
    active_from: 1927, active_to: 1988, tags: ["delta-blues"],
    bio: "Проповедник и блюзмен дельты Миссисипи, повлиявший на Роберта Джонсона и Мадди Уотерса." },
  { slug: "blind-lemon-jefferson", name: "Blind Lemon Jefferson", type: "artist", country: "США",
    active_from: 1925, active_to: 1929, tags: ["country-blues"],
    bio: "Пионер техасского кантри-блюза, один из первых коммерчески успешных блюзменов." },
  { slug: "robert-johnson", name: "Robert Johnson", type: "artist", country: "США",
    active_from: 1929, active_to: 1938, tags: ["delta-blues"],
    bio: "Легенда дельта-блюза, чьи 29 записей определили язык послевоенного блюза и рока." },
  { slug: "lead-belly", name: "Lead Belly", type: "artist", country: "США",
    active_from: 1918, active_to: 1949, tags: ["folk-blues"],
    bio: "Фолк- и блюз-музыкант, хранитель американских народных песен, повлиявший на фолк-возрождение." },
  { slug: "sister-rosetta-tharpe", name: "Sister Rosetta Tharpe", type: "artist", country: "США",
    active_from: 1938, active_to: 1973, tags: ["gospel"],
    bio: "«Крёстная мать рок-н-ролла», соединившая госпел с электрогитарой." },
  { slug: "arthur-crudup", name: "Arthur «Big Boy» Crudup", type: "artist", country: "США",
    active_from: 1939, active_to: 1974, tags: ["delta-blues"],
    bio: "Блюзмен дельты, автор «That's All Right», ставшей дебютным синглом Элвиса Пресли." },
  { slug: "big-mama-thornton", name: "Big Mama Thornton", type: "artist", country: "США",
    active_from: 1947, active_to: 1984, tags: ["rhythm-and-blues"],
    bio: "Исполнительница, первой записавшая «Hound Dog» и «Ball and Chain»." },

  // --- Electric blues / early R&R ---
  { slug: "t-bone-walker", name: "T-Bone Walker", type: "artist", country: "США",
    active_from: 1929, active_to: 1975, tags: ["electric-blues"],
    bio: "Пионер электрического блюза, во многом создавший словарь электрогитары." },
  { slug: "muddy-waters", name: "Muddy Waters", type: "artist", country: "США",
    active_from: 1941, active_to: 1983, tags: ["chicago-blues"],
    bio: "«Отец чикагского блюза», мост между дельта-блюзом и рок-н-роллом." },
  { slug: "howlin-wolf", name: "Howlin' Wolf", type: "artist", country: "США",
    active_from: 1951, active_to: 1976, tags: ["chicago-blues"],
    bio: "Мощнейший голос чикагского блюза, ученик Чарли Паттона." },
  { slug: "bb-king", name: "B.B. King", type: "artist", country: "США",
    active_from: 1949, active_to: 2015, tags: ["electric-blues"],
    bio: "«Король блюза», чья выразительная игра определила блюзовую гитару XX века." },
  { slug: "chuck-berry", name: "Chuck Berry", type: "artist", country: "США",
    active_from: 1953, active_to: 2017, tags: ["rock-and-roll"],
    bio: "Один из создателей рок-н-ролла, автор фирменных гитарных риффов жанра." },
  { slug: "little-richard", name: "Little Richard", type: "artist", country: "США",
    active_from: 1951, active_to: 2020, tags: ["rock-and-roll"],
    bio: "«Архитектор рок-н-ролла», взрывной вокал и фортепиано которого задали энергию жанра." },
  { slug: "elvis-presley", name: "Elvis Presley", type: "artist", country: "США",
    active_from: 1954, active_to: 1977, tags: ["rock-and-roll"],
    bio: "«Король рок-н-ролла», вынесший ритм-энд-блюз в мейнстрим." },
  { slug: "buddy-holly", name: "Buddy Holly", type: "artist", country: "США",
    active_from: 1955, active_to: 1959, tags: ["rock-and-roll"],
    bio: "Новатор рок-н-ролла, повлиявший на формат группы и песенное письмо 1960-х." },
  { slug: "woody-guthrie", name: "Woody Guthrie", type: "artist", country: "США",
    active_from: 1930, active_to: 1967, tags: ["folk"],
    bio: "Икона американского фолка, голос рабочего движения, кумир Боба Дилана." },
  { slug: "hank-williams", name: "Hank Williams", type: "artist", country: "США",
    active_from: 1937, active_to: 1953, tags: ["country"],
    bio: "Основоположник современного кантри, повлиявший на рок и сонграйтинг." },

  // --- 1960s rock ---
  { slug: "the-beatles", name: "The Beatles", type: "band", country: "Великобритания",
    active_from: 1960, active_to: 1970, tags: ["rock"],
    bio: "Самая влиятельная рок-группа XX века, переопределившая поп- и рок-музыку." },
  { slug: "the-rolling-stones", name: "The Rolling Stones", type: "band", country: "Великобритания",
    active_from: 1962, active_to: null, tags: ["rock", "blues-rock"],
    bio: "Группа, принёсшая чикагский блюз британской и мировой публике." },
  { slug: "bob-dylan", name: "Bob Dylan", type: "artist", country: "США",
    active_from: 1961, active_to: null, tags: ["folk-rock"],
    bio: "Поэт и музыкант, соединивший фолк с роком и изменивший роль текста в песне." },
  { slug: "jimi-hendrix", name: "Jimi Hendrix", type: "artist", country: "США",
    active_from: 1963, active_to: 1970, tags: ["psychedelic-rock"],
    bio: "Революционер электрогитары, переопределивший её звучание и технику." },
  { slug: "cream", name: "Cream", type: "band", country: "Великобритания",
    active_from: 1966, active_to: 1968, tags: ["blues-rock"],
    bio: "Первое рок-супертрио, соединившее блюз с виртуозной импровизацией." },
  { slug: "the-stooges", name: "The Stooges", type: "band", country: "США",
    active_from: 1967, active_to: 1974, tags: ["proto-punk"],
    bio: "Прото-панк-группа Игги Попа, предвосхитившая панк-рок." },

  // --- Hard rock / metal ---
  { slug: "deep-purple", name: "Deep Purple", type: "band", country: "Великобритания",
    active_from: 1968, active_to: null, tags: ["hard-rock"],
    bio: "Пионеры хард-рока и хэви-метала." },
  { slug: "black-sabbath", name: "Black Sabbath", type: "band", country: "Великобритания",
    active_from: 1968, active_to: 2017, tags: ["heavy-metal"],
    bio: "Основоположники хэви-метала." },
  { slug: "led-zeppelin", name: "Led Zeppelin", type: "band", country: "Великобритания",
    active_from: 1968, active_to: 1980, tags: ["hard-rock"],
    bio: "Группа, превратившая блюз-рок в мощный хард-рок и заложившая каноны жанра." },
  { slug: "motorhead", name: "Motörhead", type: "band", country: "Великобритания",
    active_from: 1975, active_to: 2015, tags: ["heavy-metal", "speed-metal"],
    bio: "Группа Лемми Килмистера, мост между панком и спид-металом." },
  { slug: "diamond-head", name: "Diamond Head", type: "band", country: "Великобритания",
    active_from: 1976, active_to: null, tags: ["nwobhm"],
    bio: "Группа новой волны британского хэви-метала, ключевое влияние на трэш." },
  { slug: "metallica", name: "Metallica", type: "band", country: "США",
    active_from: 1981, active_to: null, tags: ["thrash-metal"],
    bio: "Крупнейшая трэш-метал-группа, вынесшая жанр в мейнстрим." },

  // --- Punk / alternative ---
  { slug: "ramones", name: "Ramones", type: "band", country: "США",
    active_from: 1974, active_to: 1996, tags: ["punk"],
    bio: "Группа, задавшая шаблон панк-рока — быстро, коротко, мелодично." },
  { slug: "sex-pistols", name: "Sex Pistols", type: "band", country: "Великобритания",
    active_from: 1975, active_to: 1978, tags: ["punk"],
    bio: "Символ британского панк-движения." },
  { slug: "black-flag", name: "Black Flag", type: "band", country: "США",
    active_from: 1976, active_to: 1986, tags: ["hardcore-punk"],
    bio: "Пионеры хардкор-панка и DIY-сцены." },
  { slug: "pixies", name: "Pixies", type: "band", country: "США",
    active_from: 1986, active_to: null, tags: ["alternative-rock"],
    bio: "Группа, чья динамика «тихо-громко» определила альтернативный рок 1990-х." },
  { slug: "nirvana", name: "Nirvana", type: "band", country: "США",
    active_from: 1987, active_to: 1994, tags: ["grunge"],
    bio: "Группа, выведшая гранж и альтернативу в мейнстрим." },
  { slug: "stevie-ray-vaughan", name: "Stevie Ray Vaughan", type: "artist", country: "США",
    active_from: 1971, active_to: 1990, tags: ["blues-rock"],
    bio: "Гитарист, возродивший интерес к блюзу в 1980-х." },
];

// Representative photo per artist (Wikimedia Commons). Empty → initials avatar.
const imageMap = {
  "charley-patton": "https://upload.wikimedia.org/wikipedia/commons/a/af/Charley_Patton_%281929_photo_portrait%29.jpg",
  "son-house": "https://upload.wikimedia.org/wikipedia/commons/d/d9/Son_House.jpg",
  "blind-lemon-jefferson": "https://upload.wikimedia.org/wikipedia/commons/2/22/Blindlemonjeffersoncirca1926.jpg",
  "robert-johnson": "https://upload.wikimedia.org/wikipedia/en/b/b3/Robert_Johnson.png",
  "lead-belly": "https://upload.wikimedia.org/wikipedia/commons/f/f0/Leadbelly_with_Accordeon.jpg",
  "sister-rosetta-tharpe": "https://upload.wikimedia.org/wikipedia/commons/b/b2/Sister_Rosetta_Tharpe_%281938_publicity_photo_-_headshot%29.jpg",
  "arthur-crudup": "https://upload.wikimedia.org/wikipedia/commons/e/eb/Arthur_Crudup_AABF_1970_JT.jpg",
  "big-mama-thornton": "https://upload.wikimedia.org/wikipedia/en/b/b3/Thornton_Big_Mama_01.jpg",
  "t-bone-walker": "https://upload.wikimedia.org/wikipedia/en/0/04/T-Bone_Walker_in_1942.jpg",
  "muddy-waters": "https://upload.wikimedia.org/wikipedia/commons/c/ce/Muddy_Waters_november_1976.jpg",
  "howlin-wolf": "https://upload.wikimedia.org/wikipedia/commons/d/d1/Howlin_Wolf_AABF_1970_JT.jpg",
  "bb-king": "https://upload.wikimedia.org/wikipedia/commons/a/a7/Bbking.jpg",
  "chuck-berry": "https://upload.wikimedia.org/wikipedia/commons/2/20/Chuck_Berry_1957.jpg",
  "little-richard": "https://upload.wikimedia.org/wikipedia/commons/9/90/Little_Richard_1957_%28crop%29.jpg",
  "elvis-presley": "https://upload.wikimedia.org/wikipedia/commons/9/99/Elvis_Presley_promoting_Jailhouse_Rock.jpg",
  "buddy-holly": "https://upload.wikimedia.org/wikipedia/commons/0/00/Buddy_Holly_Brunswick_Records.jpg",
  "woody-guthrie": "https://upload.wikimedia.org/wikipedia/commons/0/09/Woody_Guthrie_2.jpg",
  "hank-williams": "https://upload.wikimedia.org/wikipedia/commons/6/62/Hank_Williams_Promotional_Photo.jpg",
  "the-beatles": "https://upload.wikimedia.org/wikipedia/commons/4/42/The_Beatles_1963_Dezo_Hoffman_Capitol_Records_press_photo_2.jpg",
  "the-rolling-stones": "https://upload.wikimedia.org/wikipedia/commons/1/10/The_Rolling_Stones_Summerfest_in_Milwaukee_-_2015.jpg",
  "bob-dylan": "https://upload.wikimedia.org/wikipedia/commons/2/2a/DylanYoungKilkenny140719v2_%2850_of_52%29_%2852246124397%29_%28cropped%29.jpg",
  "jimi-hendrix": "https://upload.wikimedia.org/wikipedia/commons/a/aa/Jimi_Hendrix_%281967%29_%28cropped%29.jpg",
  "cream": "https://upload.wikimedia.org/wikipedia/commons/5/58/Cream_Clapton_Bruce_Baker_1960s.jpg",
  "the-stooges": "https://upload.wikimedia.org/wikipedia/commons/1/16/Iggy_and_The_Stooges_-_4572393187.jpg",
  "deep-purple": "https://upload.wikimedia.org/wikipedia/commons/1/18/Deep_Purple_%281971%29.JPG",
  "black-sabbath": "https://upload.wikimedia.org/wikipedia/commons/4/42/Sabs.jpg",
  "led-zeppelin": "https://upload.wikimedia.org/wikipedia/commons/6/63/Led_Zeppelin_-_promotional_image_%281971%29.jpg",
  "motorhead": "https://upload.wikimedia.org/wikipedia/commons/0/0c/Motorhead-03.jpg",
  "metallica": "https://upload.wikimedia.org/wikipedia/commons/8/81/Metallica_March_2024.jpg",
  "ramones": "https://upload.wikimedia.org/wikipedia/commons/f/f8/Ramones_rocket_to_russia_photo.jpg",
  "sex-pistols": "https://upload.wikimedia.org/wikipedia/commons/1/1e/Sex_Pistols_in_Paradiso.jpg",
  "black-flag": "https://upload.wikimedia.org/wikipedia/commons/7/79/Black_Flag_performing_at_the_Electric_Ballroom_Camden_2019_%28cropped%29.jpg",
  "nirvana": "https://upload.wikimedia.org/wikipedia/commons/2/2e/Nirvana_around_1992_%28high_quality%29_%28cropped%29.jpg",
  "stevie-ray-vaughan": "https://upload.wikimedia.org/wikipedia/commons/4/43/Stevie_Ray_Vaughan_Live_1983.jpg",
};

// Wikipedia article (English) per artist — a reference link shown in the UI.
const wikiTitles = {
  "charley-patton": "Charley Patton", "son-house": "Son House",
  "blind-lemon-jefferson": "Blind Lemon Jefferson", "robert-johnson": "Robert Johnson",
  "lead-belly": "Lead Belly", "sister-rosetta-tharpe": "Sister Rosetta Tharpe",
  "arthur-crudup": "Arthur Crudup", "big-mama-thornton": "Big Mama Thornton",
  "t-bone-walker": "T-Bone Walker", "muddy-waters": "Muddy Waters",
  "howlin-wolf": "Howlin' Wolf", "bb-king": "B.B. King", "chuck-berry": "Chuck Berry",
  "little-richard": "Little Richard", "elvis-presley": "Elvis Presley",
  "buddy-holly": "Buddy Holly", "woody-guthrie": "Woody Guthrie",
  "hank-williams": "Hank Williams", "the-beatles": "The Beatles",
  "the-rolling-stones": "The Rolling Stones", "bob-dylan": "Bob Dylan",
  "jimi-hendrix": "Jimi Hendrix", "cream": "Cream (band)", "the-stooges": "The Stooges",
  "deep-purple": "Deep Purple", "black-sabbath": "Black Sabbath",
  "led-zeppelin": "Led Zeppelin", "motorhead": "Motörhead",
  "diamond-head": "Diamond Head (band)", "metallica": "Metallica", "ramones": "Ramones",
  "sex-pistols": "Sex Pistols", "black-flag": "Black Flag (band)", "pixies": "Pixies",
  "nirvana": "Nirvana (band)", "stevie-ray-vaughan": "Stevie Ray Vaughan",
};

for (const a of artists) {
  a.image = imageMap[a.slug] || "";
  const t = wikiTitles[a.slug];
  a.wiki = t ? "https://en.wikipedia.org/wiki/" + encodeURIComponent(t.replace(/ /g, "_")) : "";
}

const E = (artist, influenced_by, description, sources) =>
  ({ artist, influenced_by, description, sources });
const S = (type, citation, author = "", year = null, url = "") =>
  ({ type, citation, author, year, url });

export const influences = [
  // Delta blues lineage
  E("son-house", "charley-patton", "Сон Хаус перенял манеру дельта-блюза, играя рядом с Паттоном.",
    [S("encyclopedia", "AllMusic: Son House формировался в окружении Чарли Паттона.", "AllMusic")]),
  E("robert-johnson", "son-house", "Сон Хаус лично наблюдал за становлением молодого Джонсона и вспоминал об этом.",
    [S("interview", "Сон Хаус неоднократно рассказывал, как Роберт Джонсон учился у местных блюзменов дельты.", "Son House", 1965)]),
  E("robert-johnson", "charley-patton", "Репертуар и приёмы Паттона вошли в язык Джонсона.",
    [S("encyclopedia", "Музыковедческие разборы прослеживают паттоновские мотивы у Джонсона.", "Grove Music")]),
  E("arthur-crudup", "son-house", "Крудап впитал традицию дельта-блюза, идущую от Сон Хауса.",
    [S("encyclopedia", "Биографы относят Крудапа к дельта-блюзовой линии Сон Хауса.", "AllMusic")]),
  E("t-bone-walker", "blind-lemon-jefferson", "Подростком Уокер водил слепого Лемона Джефферсона и учился у него.",
    [S("encyclopedia", "T-Bone Walker мальчиком сопровождал Blind Lemon Jefferson по улицам Далласа.", "AllMusic")]),

  // Electric blues
  E("muddy-waters", "son-house", "Мадди Уотерс называл Сон Хауса своим главным учителем.",
    [S("interview", "Muddy Waters: «Son House — вот кто на меня действительно повлиял».", "Muddy Waters", 1971)]),
  E("muddy-waters", "robert-johnson", "Мадди перенял репертуар и слайд-технику Роберта Джонсона.",
    [S("encyclopedia", "Записи Library of Congress фиксируют влияние Джонсона на раннего Уотерса.", "Library of Congress")]),
  E("howlin-wolf", "charley-patton", "Чарли Паттон лично учил молодого Хаулин Вульфа игре и подаче.",
    [S("encyclopedia", "Howlin' Wolf учился у Чарли Паттона на плантации Докери.", "AllMusic")]),
  E("bb-king", "t-bone-walker", "Би Би Кинг говорил, что услышав Уокера, понял, каким хочет быть гитаристом.",
    [S("autobiography", "B.B. King, «Blues All Around Me»: услышанный T-Bone Walker определил его выбор.", "B.B. King", 1996)]),
  E("bb-king", "blind-lemon-jefferson", "Записи Блайнд Лемона звучали в доме Кинга с детства.",
    [S("autobiography", "B.B. King вспоминал пластинки Blind Lemon Jefferson как раннее влияние.", "B.B. King", 1996)]),

  // Rock'n'roll
  E("chuck-berry", "muddy-waters", "Именно Мадди Уотерс привёл Чака Берри на лейбл Chess.",
    [S("autobiography", "Chuck Berry, «The Autobiography»: знакомство и влияние Мадди Уотерса.", "Chuck Berry", 1987)]),
  E("chuck-berry", "t-bone-walker", "Сценические дакхвок-движения и гитарные ходы восходят к Уокеру.",
    [S("encyclopedia", "Историки рок-н-ролла прослеживают приёмы Берри к T-Bone Walker.", "Rolling Stone")]),
  E("little-richard", "sister-rosetta-tharpe", "Сестра Розетта вывела юного Литла Ричарда на сцену.",
    [S("documentary", "Док. фильм «The Godmother of Rock & Roll»: Тарп пригласила подростка Ричарда петь.", "", 2011)]),
  E("elvis-presley", "arthur-crudup", "Дебютный сингл Элвиса — кавер «That's All Right» Артура Крудапа.",
    [S("interview", "Elvis: «Если бы я мог петь как Артур Крудап, я был бы счастлив».", "Elvis Presley", 1956, "https://en.wikipedia.org/wiki/That%27s_All_Right")]),
  E("elvis-presley", "big-mama-thornton", "«Hound Dog» Элвиса — версия песни, впервые записанной Big Mama Thornton.",
    [S("encyclopedia", "Оригинал «Hound Dog» записан Big Mama Thornton в 1952 году.", "AllMusic", 1952, "https://en.wikipedia.org/wiki/Hound_Dog_(song)")]),
  E("elvis-presley", "sister-rosetta-tharpe", "Госпел-фразировка Тарп слышна в ранней манере Элвиса.",
    [S("documentary", "BBC: влияние Sister Rosetta Tharpe на вокал раннего рок-н-ролла, включая Элвиса.", "BBC")]),

  // Folk / country to Dylan
  E("bob-dylan", "woody-guthrie", "Дилан приехал в Нью-Йорк, чтобы навестить кумира Вуди Гатри.",
    [S("autobiography", "Bob Dylan, «Chronicles, Vol. 1»: Гатри как определяющее влияние.", "Bob Dylan", 2004, "https://en.wikipedia.org/wiki/Chronicles,_Volume_One")]),
  E("bob-dylan", "robert-johnson", "Дилан подробно описывал, как пластинки Джонсона перевернули его письмо.",
    [S("autobiography", "Bob Dylan, «Chronicles, Vol. 1»: влияние Роберта Джонсона на тексты.", "Bob Dylan", 2004)]),
  E("bob-dylan", "hank-williams", "Дилан называл песни Хэнка Уильямса школой сонграйтинга.",
    [S("autobiography", "Bob Dylan, «Chronicles, Vol. 1»: Хэнк Уильямс как учитель.", "Bob Dylan", 2004)]),

  // British Invasion
  E("the-beatles", "chuck-berry", "Битлз исполняли и записывали песни Чака Берри.",
    [S("interview", "John Lennon: «Если дать рок-н-роллу другое имя, это будет Chuck Berry».", "John Lennon", 1972)]),
  E("the-beatles", "elvis-presley", "Элвис был главным юношеским образцом для участников группы.",
    [S("interview", "John Lennon: «До Элвиса не было ничего».", "John Lennon")]),
  E("the-beatles", "little-richard", "Пол Маккартни перенял крик-вокал у Литла Ричарда.",
    [S("interview", "Paul McCartney рассказывал, что учился вокалу по записям Little Richard.", "Paul McCartney")]),
  E("the-beatles", "buddy-holly", "Само название и формат группы вдохновлены The Crickets Бадди Холли.",
    [S("encyclopedia", "Имя «Beatles» — отсылка к «Crickets»; влияние Buddy Holly на формат группы.", "AllMusic")]),
  E("the-rolling-stones", "muddy-waters", "Группа взяла название из песни Мадди Уотерса «Rollin' Stone».",
    [S("encyclopedia", "Название The Rolling Stones происходит от песни Мадди Уотерса.", "AllMusic", 1962, "https://en.wikipedia.org/wiki/Rollin%27_Stone_(Muddy_Waters_song)")]),
  E("the-rolling-stones", "chuck-berry", "Ранний репертуар Stones строился на песнях Чака Берри.",
    [S("interview", "Keith Richards многократно называл Chuck Berry главным влиянием на свою игру.", "Keith Richards")]),
  E("the-rolling-stones", "robert-johnson", "Stones записали «Love in Vain» и «Stop Breaking Down» Джонсона.",
    [S("encyclopedia", "Кавер-версии Роберта Джонсона в репертуаре The Rolling Stones.", "AllMusic")]),
  E("the-rolling-stones", "howlin-wolf", "Stones настояли на участии Хаулин Вульфа в эфире Shindig!.",
    [S("documentary", "В 1965 Stones вывели Howlin' Wolf на ТВ-шоу Shindig!.", "", 1965)]),

  // Hendrix roots
  E("jimi-hendrix", "muddy-waters", "Хендрикс вспоминал, что первый блюз, напугавший его, был у Мадди Уотерса.",
    [S("interview", "Jimi Hendrix: «Первый гитарист, о котором я узнал, был Muddy Waters».", "Jimi Hendrix", 1968)]),
  E("jimi-hendrix", "bb-king", "Хендрикс впитал выразительную блюзовую фразировку Би Би Кинга.",
    [S("encyclopedia", "Биографы отмечают влияние B.B. King на блюзовую сторону Хендрикса.", "Rolling Stone")]),
  E("jimi-hendrix", "little-richard", "Хендрикс играл в гастрольной группе Литла Ричарда.",
    [S("encyclopedia", "Jimi Hendrix был гитаристом в группе Little Richard в 1964–65.", "AllMusic", 1965)]),
  E("jimi-hendrix", "bob-dylan", "Кавер «All Along the Watchtower» — дань влиянию Дилана.",
    [S("interview", "Hendrix признавал огромное влияние песен Боба Дилана на свой подход к тексту.", "Jimi Hendrix")]),

  // Cream
  E("cream", "robert-johnson", "Cream сделали хитом «Crossroads» Роберта Джонсона.",
    [S("encyclopedia", "Cream популяризировали «Cross Road Blues» Роберта Джонсона.", "AllMusic", 1968, "https://en.wikipedia.org/wiki/Cross_Road_Blues")]),
  E("cream", "muddy-waters", "Чикагский блюз Уотерса — фундамент репертуара Cream.",
    [S("interview", "Eric Clapton называл Мадди Уотерса крёстным отцом всего, что он делает.", "Eric Clapton")]),

  // Hard rock / metal
  E("led-zeppelin", "howlin-wolf", "Zeppelin адаптировали «How Many More Times» из песен Хаулин Вульфа.",
    [S("encyclopedia", "Ряд тем Led Zeppelin восходит к Howlin' Wolf и Willie Dixon.", "AllMusic")]),
  E("led-zeppelin", "robert-johnson", "«Travelling Riverside Blues» — прямая отсылка к Джонсону.",
    [S("encyclopedia", "Led Zeppelin записали «Travelling Riverside Blues» Роберта Джонсона.", "AllMusic", null, "https://en.wikipedia.org/wiki/Travelling_Riverside_Blues")]),
  E("led-zeppelin", "muddy-waters", "Чикагский электроблюз Уотерса — основа тяжёлого блюз-рока Zeppelin.",
    [S("interview", "Jimmy Page называл Чесс-блюз, включая Мадди Уотерса, ключевым влиянием.", "Jimmy Page")]),
  E("led-zeppelin", "jimi-hendrix", "Подход Хендрикса к тяжёлому звуку гитары повлиял на Джимми Пейджа.",
    [S("encyclopedia", "Гитарный звук Хендрикса — общий ориентир для хард-рока конца 1960-х.", "Rolling Stone")]),
  E("deep-purple", "jimi-hendrix", "Ритчи Блэкмор называл громкость и драйв Хендрикса ориентиром.",
    [S("interview", "Ritchie Blackmore отмечал влияние Хендрикса на тяжесть звучания.", "Ritchie Blackmore")]),
  E("black-sabbath", "cream", "Ранний Sabbath отталкивался от тяжёлого блюз-рока Cream.",
    [S("interview", "Tony Iommi называл Cream одним из первых ориентиров группы.", "Tony Iommi")]),
  E("motorhead", "jimi-hendrix", "Лемми работал роуди у Хендрикса и считал его огромным влиянием.",
    [S("autobiography", "Lemmy, «White Line Fever»: работа с Хендриксом и его влияние.", "Lemmy Kilmister", 2002, "https://en.wikipedia.org/wiki/White_Line_Fever_(book)")]),
  E("motorhead", "little-richard", "Лемми называл рок-н-ролл Литла Ричарда корнем своей энергетики.",
    [S("autobiography", "Lemmy, «White Line Fever»: любовь к рок-н-роллу Little Richard.", "Lemmy Kilmister", 2002)]),
  E("motorhead", "the-beatles", "Лемми видел ранних Beatles живьём и считал их жёсткой рок-группой.",
    [S("interview", "Lemmy многократно говорил, что The Beatles — недооценённо тяжёлая группа.", "Lemmy Kilmister")]),
  E("diamond-head", "black-sabbath", "NWOBHM Diamond Head выросла на риффах Black Sabbath.",
    [S("encyclopedia", "Diamond Head относят к наследникам Black Sabbath и Led Zeppelin.", "AllMusic")]),
  E("diamond-head", "led-zeppelin", "Структуры песен Diamond Head наследуют Led Zeppelin.",
    [S("encyclopedia", "Критики отмечают цеппелиновское влияние на Diamond Head.", "AllMusic")]),
  E("metallica", "motorhead", "Скорость и напор Motörhead — прямой предок трэша Metallica.",
    [S("interview", "Lars Ulrich называл Motörhead одним из главных влияний Metallica.", "Lars Ulrich")]),
  E("metallica", "diamond-head", "Metallica записали несколько каверов Diamond Head.",
    [S("encyclopedia", "Metallica исполняли «Am I Evil?» и др. песни Diamond Head.", "AllMusic", null, "https://en.wikipedia.org/wiki/Am_I_Evil%3F")]),
  E("metallica", "black-sabbath", "Тяжесть Black Sabbath — фундамент звука Metallica.",
    [S("interview", "Участники Metallica называли Black Sabbath основой тяжёлой музыки.", "Metallica")]),
  E("metallica", "deep-purple", "Ранний Ларс Ульрих вдохновлялся напором Deep Purple.",
    [S("interview", "Lars Ulrich вспоминал Deep Purple среди формирующих влияний.", "Lars Ulrich")]),
  E("metallica", "led-zeppelin", "Джеймс Хэтфилд называл Led Zeppelin ключевым ориентиром.",
    [S("interview", "James Hetfield отмечал влияние Led Zeppelin на риффы.", "James Hetfield")]),

  // Punk lineage
  E("ramones", "the-stooges", "Сырой прото-панк Stooges — прямой предок Ramones.",
    [S("encyclopedia", "The Stooges называют ключевым влиянием на Ramones.", "AllMusic")]),
  E("ramones", "the-beatles", "Мелодизм и короткие песни Ramones — наследие Beatles.",
    [S("interview", "Johnny Ramone называл The Beatles причиной взять гитару.", "Johnny Ramone")]),
  E("sex-pistols", "the-stooges", "Иэн и Игги Поп — образец сценического панка для Pistols.",
    [S("encyclopedia", "The Stooges и Iggy Pop — ключевое влияние на Sex Pistols.", "AllMusic")]),
  E("sex-pistols", "ramones", "Турне и записи Ramones подтолкнули британскую панк-сцену.",
    [S("documentary", "Док. материалы фиксируют влияние Ramones на лондонский панк 1976.", "", 1976)]),
  E("black-flag", "the-stooges", "Хардкор Black Flag вырос из агрессии Stooges.",
    [S("encyclopedia", "The Stooges — общий предок калифорнийского хардкора, включая Black Flag.", "AllMusic")]),

  // Grunge
  E("nirvana", "pixies", "Кобейн признавал, что «Smells Like Teen Spirit» — попытка написать песню Pixies.",
    [S("interview", "Kurt Cobain (Rolling Stone, 1994): «Я попросту пытался копировать Pixies».", "Kurt Cobain", 1994, "https://en.wikipedia.org/wiki/Smells_Like_Teen_Spirit")]),
  E("nirvana", "the-stooges", "Альбом «Raw Power» Stooges Кобейн называл любимым.",
    [S("interview", "Kurt Cobain ставил «Raw Power» The Stooges на первое место в списке любимых альбомов.", "Kurt Cobain")]),
  E("nirvana", "black-flag", "Хардкор Black Flag — часть панк-фундамента Nirvana.",
    [S("interview", "Kurt Cobain называл Black Flag среди формирующих панк-влияний.", "Kurt Cobain")]),
  E("nirvana", "black-sabbath", "Тяжёлые риффы Nirvana наследуют Black Sabbath.",
    [S("interview", "Участники Nirvana называли Black Sabbath источником тяжести звука.", "Nirvana")]),
  E("nirvana", "lead-belly", "Финал «Unplugged» — кавер «Where Did You Sleep Last Night» Лед Белли.",
    [S("interview", "Kurt Cobain представил песню как вещь Lead Belly, своего любимого исполнителя.", "Kurt Cobain", 1993, "https://en.wikipedia.org/wiki/Where_Did_You_Sleep_Last_Night")]),
  E("pixies", "the-stooges", "Громко-тихая динамика Pixies восходит к панк-энергии Stooges.",
    [S("encyclopedia", "Влияние The Stooges на альтернативный рок, включая Pixies.", "AllMusic")]),

  // Blues revival
  E("stevie-ray-vaughan", "jimi-hendrix", "Воган открыто строил репертуар вокруг каверов Хендрикса.",
    [S("encyclopedia", "Stevie Ray Vaughan исполнял «Voodoo Child» и др. вещи Хендрикса.", "AllMusic")]),
  E("stevie-ray-vaughan", "bb-king", "Блюзовая фразировка Вогана наследует Би Би Кингу.",
    [S("interview", "SRV называл B.B. King в числе главных учителей блюза.", "Stevie Ray Vaughan")]),
];
