// Seed dataset for MusicRoots.
// Edges read "artist  <-  influenced_by" (A draws influence from B).
// Every edge carries at least one confirming source.

export const artists = [
  // --- Delta blues roots ---
  { slug: "charley-patton", name: "Charley Patton", type: "artist", country: "США",
    active_from: 1910, active_to: 1934, tags: ["delta-blues"],
    bio: "Один из основателей дельта-блюза, «отец Delta Blues», учитель целого поколения блюзменов Миссисипи." },
  { slug: "son-house", name: "Son House", type: "artist", country: "США",
    active_from: 1927, active_to: 1988, tags: ["delta-blues"],
    bio: "Проповедник и блюзмен дельты Миссисипи, повлиявший на Роберта Джонсона и Мадди Уотерса." },
  { slug: "blind-lemon-jefferson", name: "Blind Lemon Jefferson", type: "artist", country: "США",
    active_from: 1925, active_to: 1929, tags: ["country-blues"],
    bio: "Пионер техасского кантри-блюза, один из первых коммерчески успешных блюзменов." },
  { slug: "robert-johnson", name: "Robert Johnson", type: "artist", country: "США",
    active_from: 1929, active_to: 1938, tags: ["delta-blues"],
    bio: "Легенда дельта-блюза, чьи 29 записей определили язык послевоенного блюза и рока." },
  { slug: "lead-belly", name: "Lead Belly", type: "artist", country: "США",
    active_from: 1918, active_to: 1949, tags: ["folk-blues"],
    bio: "Фолк- и блюз-музыкант, хранитель американских народных песен, повлиявший на фолк-возрождение." },
  { slug: "sister-rosetta-tharpe", name: "Sister Rosetta Tharpe", type: "artist", country: "США",
    active_from: 1938, active_to: 1973, tags: ["gospel"],
    bio: "«Крёстная мать рок-н-ролла», соединившая госпел с электрогитарой." },
  { slug: "arthur-crudup", name: "Arthur «Big Boy» Crudup", type: "artist", country: "США",
    active_from: 1939, active_to: 1974, tags: ["delta-blues"],
    bio: "Блюзмен дельты, автор «That's All Right», ставшей дебютным синглом Элвиса Пресли." },
  { slug: "big-mama-thornton", name: "Big Mama Thornton", type: "artist", country: "США",
    active_from: 1947, active_to: 1984, tags: ["rhythm-and-blues"],
    bio: "Исполнительница, первой записавшая «Hound Dog» и «Ball and Chain»." },

  // --- Electric blues / early R&R ---
  { slug: "t-bone-walker", name: "T-Bone Walker", type: "artist", country: "США",
    active_from: 1929, active_to: 1975, tags: ["electric-blues"],
    bio: "Пионер электрического блюза, во многом создавший словарь электрогитары." },
  { slug: "muddy-waters", name: "Muddy Waters", type: "artist", country: "США",
    active_from: 1941, active_to: 1983, tags: ["chicago-blues"],
    bio: "«Отец чикагского блюза», мост между дельта-блюзом и рок-н-роллом." },
  { slug: "howlin-wolf", name: "Howlin' Wolf", type: "artist", country: "США",
    active_from: 1951, active_to: 1976, tags: ["chicago-blues"],
    bio: "Мощнейший голос чикагского блюза, ученик Чарли Паттона." },
  { slug: "bb-king", name: "B.B. King", type: "artist", country: "США",
    active_from: 1949, active_to: 2015, tags: ["electric-blues"],
    bio: "«Король блюза», чья выразительная игра определила блюзовую гитару XX века." },
  { slug: "chuck-berry", name: "Chuck Berry", type: "artist", country: "США",
    active_from: 1953, active_to: 2017, tags: ["rock-and-roll"],
    bio: "Один из создателей рок-н-ролла, автор фирменных гитарных риффов жанра." },
  { slug: "little-richard", name: "Little Richard", type: "artist", country: "США",
    active_from: 1951, active_to: 2020, tags: ["rock-and-roll"],
    bio: "«Архитектор рок-н-ролла», взрывной вокал и фортепиано которого задали энергию жанра." },
  { slug: "elvis-presley", name: "Elvis Presley", type: "artist", country: "США",
    active_from: 1954, active_to: 1977, tags: ["rock-and-roll"],
    bio: "«Король рок-н-ролла», вынесший ритм-энд-блюз в мейнстрим." },
  { slug: "buddy-holly", name: "Buddy Holly", type: "artist", country: "США",
    active_from: 1955, active_to: 1959, tags: ["rock-and-roll"],
    bio: "Новатор рок-н-ролла, повлиявший на формат группы и песенное письмо 1960-х." },
  { slug: "woody-guthrie", name: "Woody Guthrie", type: "artist", country: "США",
    active_from: 1930, active_to: 1967, tags: ["folk"],
    bio: "Икона американского фолка, голос рабочего движения, кумир Боба Дилана." },
  { slug: "hank-williams", name: "Hank Williams", type: "artist", country: "США",
    active_from: 1937, active_to: 1953, tags: ["country"],
    bio: "Основоположник современного кантри, повлиявший на рок и сонграйтинг." },

  // --- 1960s rock ---
  { slug: "the-beatles", name: "The Beatles", type: "band", country: "Великобритания",
    active_from: 1960, active_to: 1970, tags: ["rock"],
    bio: "Самая влиятельная рок-группа XX века, переопределившая поп- и рок-музыку." },
  { slug: "the-rolling-stones", name: "The Rolling Stones", type: "band", country: "Великобритания",
    active_from: 1962, active_to: null, tags: ["rock", "blues-rock"],
    bio: "Группа, принёсшая чикагский блюз британской и мировой публике." },
  { slug: "bob-dylan", name: "Bob Dylan", type: "artist", country: "США",
    active_from: 1961, active_to: null, tags: ["folk-rock"],
    bio: "Поэт и музыкант, соединивший фолк с роком и изменивший роль текста в песне." },
  { slug: "jimi-hendrix", name: "Jimi Hendrix", type: "artist", country: "США",
    active_from: 1963, active_to: 1970, tags: ["psychedelic-rock"],
    bio: "Революционер электрогитары, переопределивший её звучание и технику." },
  { slug: "cream", name: "Cream", type: "band", country: "Великобритания",
    active_from: 1966, active_to: 1968, tags: ["blues-rock"],
    bio: "Первое рок-супертрио, соединившее блюз с виртуозной импровизацией." },
  { slug: "the-stooges", name: "The Stooges", type: "band", country: "США",
    active_from: 1967, active_to: 1974, tags: ["proto-punk"],
    bio: "Прото-панк-группа Игги Попа, предвосхитившая панк-рок." },

  // --- Hard rock / metal ---
  { slug: "deep-purple", name: "Deep Purple", type: "band", country: "Великобритания",
    active_from: 1968, active_to: null, tags: ["hard-rock"],
    bio: "Пионеры хард-рока и хэви-метала." },
  { slug: "black-sabbath", name: "Black Sabbath", type: "band", country: "Великобритания",
    active_from: 1968, active_to: 2017, tags: ["heavy-metal"],
    bio: "Основоположники хэви-метала." },
  { slug: "led-zeppelin", name: "Led Zeppelin", type: "band", country: "Великобритания",
    active_from: 1968, active_to: 1980, tags: ["hard-rock"],
    bio: "Группа, превратившая блюз-рок в мощный хард-рок и заложившая каноны жанра." },
  { slug: "motorhead", name: "Motörhead", type: "band", country: "Великобритания",
    active_from: 1975, active_to: 2015, tags: ["heavy-metal", "speed-metal"],
    bio: "Группа Лемми Килмистера, мост между панком и спид-металом." },
  { slug: "diamond-head", name: "Diamond Head", type: "band", country: "Великобритания",
    active_from: 1976, active_to: null, tags: ["nwobhm"],
    bio: "Группа новой волны британского хэви-метала, ключевое влияние на трэш." },
  { slug: "metallica", name: "Metallica", type: "band", country: "США",
    active_from: 1981, active_to: null, tags: ["thrash-metal"],
    bio: "Крупнейшая трэш-метал-группа, вынесшая жанр в мейнстрим." },

  // --- Punk / alternative ---
  { slug: "ramones", name: "Ramones", type: "band", country: "США",
    active_from: 1974, active_to: 1996, tags: ["punk"],
    bio: "Группа, задавшая шаблон панк-рока — быстро, коротко, мелодично." },
  { slug: "sex-pistols", name: "Sex Pistols", type: "band", country: "Великобритания",
    active_from: 1975, active_to: 1978, tags: ["punk"],
    bio: "Символ британского панк-движения." },
  { slug: "black-flag", name: "Black Flag", type: "band", country: "США",
    active_from: 1976, active_to: 1986, tags: ["hardcore-punk"],
    bio: "Пионеры хардкор-панка и DIY-сцены." },
  { slug: "pixies", name: "Pixies", type: "band", country: "США",
    active_from: 1986, active_to: null, tags: ["alternative-rock"],
    bio: "Группа, чья динамика «тихо-громко» определила альтернативный рок 1990-х." },
  { slug: "nirvana", name: "Nirvana", type: "band", country: "США",
    active_from: 1987, active_to: 1994, tags: ["grunge"],
    bio: "Группа, выведшая гранж и альтернативу в мейнстрим." },
  { slug: "stevie-ray-vaughan", name: "Stevie Ray Vaughan", type: "artist", country: "США",
    active_from: 1971, active_to: 1990, tags: ["blues-rock"],
    bio: "Гитарист, возродивший интерес к блюзу в 1980-х." },

  // --- Avant-garde / art-rock / electronic / industrial cluster ---
  { slug: "fannie-charles-dillon", name: "Fannie Charles Dillon", type: "artist", country: "USA",
    active_from: 1910, active_to: 1947, tags: ["classical", "experimental"],
    bio: "American composer, pianist and educator known for transcribing bird calls into musical scores. Taught at Los Angeles High School where John Cage was among her students in the late 1920s." },
  { slug: "john-cage", name: "John Cage", type: "artist", country: "USA",
    active_from: 1938, active_to: 1992, tags: ["avant-garde", "experimental", "classical"],
    bio: "American composer whose prepared piano, chance operations (aleatoric music) and 4'33\" redefined the boundaries of music — a foundational figure for every strand of experimental and electronic art." },
  { slug: "karlheinz-stockhausen", name: "Karlheinz Stockhausen", type: "artist", country: "Германия",
    active_from: 1950, active_to: 2007, tags: ["avant-garde", "electronic"],
    bio: "Композитор-авангардист, пионер электронной и алеаторической музыки, повлиявший на рок и электронику." },
  { slug: "nina-simone", name: "Nina Simone", type: "artist", country: "США",
    active_from: 1954, active_to: 2003, tags: ["jazz", "soul"],
    bio: "Певица, пианистка и активистка, соединившая классику, джаз, госпел и соул в уникальную манеру." },
  { slug: "the-velvet-underground", name: "The Velvet Underground", type: "band", country: "США",
    active_from: 1964, active_to: 1973, tags: ["art-rock", "proto-punk"],
    bio: "Группа Лу Рида и Джона Кейла, чей авангардный рок стал фундаментом арт-рока, панка и инди." },
  { slug: "david-bowie", name: "David Bowie", type: "artist", country: "Великобритания",
    active_from: 1962, active_to: 2016, tags: ["art-rock", "glam-rock"],
    bio: "Хамелеон рок-музыки, соединивший арт-рок, глэм и электронику и переопределивший образ артиста." },
  { slug: "brian-eno", name: "Brian Eno", type: "artist", country: "Великобритания",
    active_from: 1971, active_to: null, tags: ["ambient", "art-rock", "electronic"],
    bio: "Музыкант и продюсер, основатель эмбиента, участник Roxy Music, архитектор студийного звука." },
  { slug: "kate-bush", name: "Kate Bush", type: "artist", country: "Великобритания",
    active_from: 1978, active_to: null, tags: ["art-pop"],
    bio: "Певица и автор, новатор арт-попа, соединившая литературный текст, театральность и студийные эксперименты." },
  { slug: "cabaret-voltaire", name: "Cabaret Voltaire", type: "band", country: "Великобритания",
    active_from: 1973, active_to: null, tags: ["industrial", "electronic"],
    bio: "Шеффилдская группа, пионеры индустриальной музыки и раннего электронного эксперимента." },
  { slug: "genesis-p-orridge", name: "Genesis P-Orridge", type: "artist", country: "Великобритания",
    active_from: 1969, active_to: 2020, tags: ["industrial"],
    bio: "Основатель Throbbing Gristle и Psychic TV, идеолог индустриальной музыки и перформанса." },

  // --- Jazz / New Orleans roots cluster ---
  { slug: "king-oliver", name: "King Oliver", type: "artist", country: "USA",
    active_from: 1915, active_to: 1938, tags: ["jazz", "new-orleans"],
    bio: "New Orleans cornet king and mentor of Louis Armstrong, whose Creole Jazz Band set the template for Chicago jazz." },
  { slug: "duke-ellington", name: "Duke Ellington", type: "artist", country: "USA",
    active_from: 1917, active_to: 1974, tags: ["jazz", "big-band"],
    bio: "Composer, pianist and bandleader whose half-century career made him the defining figure of American jazz." },
  { slug: "louis-armstrong", name: "Louis Armstrong", type: "artist", country: "USA",
    active_from: 1919, active_to: 1971, tags: ["jazz", "new-orleans"],
    bio: "Satchmo — the first great jazz soloist and global ambassador of jazz, who transformed improvisation and trumpet technique." },
  { slug: "django-reinhardt", name: "Django Reinhardt", type: "artist", country: "Belgium",
    active_from: 1928, active_to: 1953, tags: ["jazz", "gypsy-jazz"],
    bio: "Romani-Belgian guitarist who co-created Gypsy jazz and remains one of the most singular voices in the history of guitar." },

  // --- Soul / funk / R&B cluster ---
  { slug: "jackie-wilson", name: "Jackie Wilson", type: "artist", country: "USA",
    active_from: 1953, active_to: 1984, tags: ["rhythm-and-blues", "soul"],
    bio: "R&B showman nicknamed 'Mr. Excitement', whose acrobatic stage performances set the template that Michael Jackson would perfect." },
  { slug: "james-brown", name: "James Brown", type: "artist", country: "USA",
    active_from: 1956, active_to: 2006, tags: ["funk", "soul", "rhythm-and-blues"],
    bio: "The Godfather of Soul and Father of Funk, whose explosive stage presence and rhythmic innovations defined soul, funk and hip-hop." },
  { slug: "curtis-mayfield", name: "Curtis Mayfield", type: "artist", country: "USA",
    active_from: 1958, active_to: 1999, tags: ["soul", "funk", "rhythm-and-blues"],
    bio: "Soul and funk visionary whose socially charged music with The Impressions and his solo career influenced generations of artists." },
  { slug: "marvin-gaye", name: "Marvin Gaye", type: "artist", country: "USA",
    active_from: 1961, active_to: 1984, tags: ["soul", "rhythm-and-blues"],
    bio: "Motown star who evolved from pop hits to socially conscious albums, redefining what soul music could say and feel." },
  { slug: "michael-jackson", name: "Michael Jackson", type: "artist", country: "USA",
    active_from: 1964, active_to: 2009, tags: ["pop", "rhythm-and-blues", "funk"],
    bio: "The King of Pop, whose synthesis of R&B, soul and pop combined with revolutionary dance defined modern pop music globally." },

  // --- Reggae ---
  { slug: "bob-marley", name: "Bob Marley", type: "artist", country: "Jamaica",
    active_from: 1963, active_to: 1981, tags: ["reggae"],
    bio: "The face of reggae worldwide, who fused Jamaican roots music with soul and Rastafari spirituality to reach audiences across generations." },

  // --- Krautrock / electronic ---
  { slug: "kraftwerk", name: "Kraftwerk", type: "band", country: "Germany",
    active_from: 1969, active_to: null, tags: ["electronic", "krautrock"],
    bio: "Düsseldorf synthesizer pioneers who invented the template for electronic pop, influencing virtually every strand of modern electronic music." },

  // --- Post-punk / new wave ---
  { slug: "joy-division", name: "Joy Division", type: "band", country: "United Kingdom",
    active_from: 1976, active_to: 1980, tags: ["post-punk", "gothic-rock"],
    bio: "Mancunian post-punk band whose bleak atmosphere and Ian Curtis's commanding presence defined the sound of late-1970s alternative music." },
  { slug: "new-order", name: "New Order", type: "band", country: "United Kingdom",
    active_from: 1980, active_to: null, tags: ["new-wave", "electronic"],
    bio: "Formed from the ashes of Joy Division, New Order fused post-punk with electronic dance music, pioneering the bridge between indie and club culture." },

  // --- Glam / classic rock ---
  { slug: "queen", name: "Queen", type: "band", country: "United Kingdom",
    active_from: 1970, active_to: null, tags: ["rock", "glam-rock", "art-rock"],
    bio: "Maximalist British rock band whose operatic grandeur, layered arrangements and showmanship became the stadium-rock blueprint." },
];

// Representative photo per artist (Wikimedia Commons). Empty → initials avatar.
const imageMap = {
  "charley-patton": "https://upload.wikimedia.org/wikipedia/commons/a/af/Charley_Patton_%281929_photo_portrait%29.jpg",
  "son-house": "https://upload.wikimedia.org/wikipedia/commons/d/d9/Son_House.jpg",
  "blind-lemon-jefferson": "https://upload.wikimedia.org/wikipedia/commons/2/22/Blindlemonjeffersoncirca1926.jpg",
  "robert-johnson": "https://upload.wikimedia.org/wikipedia/en/b/b3/Robert_Johnson.png",
  "lead-belly": "https://upload.wikimedia.org/wikipedia/commons/f/f0/Leadbelly_with_Accordeon.jpg",
  "sister-rosetta-tharpe": "https://upload.wikimedia.org/wikipedia/commons/b/b2/Sister_Rosetta_Tharpe_%281938_publicity_photo_-_headshot%29.jpg",
  "arthur-crudup": "https://upload.wikimedia.org/wikipedia/commons/e/eb/Arthur_Crudup_AABF_1970_JT.jpg",
  "big-mama-thornton": "https://upload.wikimedia.org/wikipedia/en/b/b3/Thornton_Big_Mama_01.jpg",
  "t-bone-walker": "https://upload.wikimedia.org/wikipedia/en/0/04/T-Bone_Walker_in_1942.jpg",
  "muddy-waters": "https://upload.wikimedia.org/wikipedia/commons/c/ce/Muddy_Waters_november_1976.jpg",
  "howlin-wolf": "https://upload.wikimedia.org/wikipedia/commons/d/d1/Howlin_Wolf_AABF_1970_JT.jpg",
  "bb-king": "https://upload.wikimedia.org/wikipedia/commons/a/a7/Bbking.jpg",
  "chuck-berry": "https://upload.wikimedia.org/wikipedia/commons/2/20/Chuck_Berry_1957.jpg",
  "little-richard": "https://upload.wikimedia.org/wikipedia/commons/9/90/Little_Richard_1957_%28crop%29.jpg",
  "elvis-presley": "https://upload.wikimedia.org/wikipedia/commons/9/99/Elvis_Presley_promoting_Jailhouse_Rock.jpg",
  "buddy-holly": "https://upload.wikimedia.org/wikipedia/commons/0/00/Buddy_Holly_Brunswick_Records.jpg",
  "woody-guthrie": "https://upload.wikimedia.org/wikipedia/commons/0/09/Woody_Guthrie_2.jpg",
  "hank-williams": "https://upload.wikimedia.org/wikipedia/commons/6/62/Hank_Williams_Promotional_Photo.jpg",
  "the-beatles": "https://upload.wikimedia.org/wikipedia/commons/4/42/The_Beatles_1963_Dezo_Hoffman_Capitol_Records_press_photo_2.jpg",
  "the-rolling-stones": "https://upload.wikimedia.org/wikipedia/commons/1/10/The_Rolling_Stones_Summerfest_in_Milwaukee_-_2015.jpg",
  "bob-dylan": "https://upload.wikimedia.org/wikipedia/commons/2/2a/DylanYoungKilkenny140719v2_%2850_of_52%29_%2852246124397%29_%28cropped%29.jpg",
  "jimi-hendrix": "https://upload.wikimedia.org/wikipedia/commons/a/aa/Jimi_Hendrix_%281967%29_%28cropped%29.jpg",
  "cream": "https://upload.wikimedia.org/wikipedia/commons/5/58/Cream_Clapton_Bruce_Baker_1960s.jpg",
  "the-stooges": "https://upload.wikimedia.org/wikipedia/commons/1/16/Iggy_and_The_Stooges_-_4572393187.jpg",
  "deep-purple": "https://upload.wikimedia.org/wikipedia/commons/1/18/Deep_Purple_%281971%29.JPG",
  "black-sabbath": "https://upload.wikimedia.org/wikipedia/commons/4/42/Sabs.jpg",
  "led-zeppelin": "https://upload.wikimedia.org/wikipedia/commons/6/63/Led_Zeppelin_-_promotional_image_%281971%29.jpg",
  "motorhead": "https://upload.wikimedia.org/wikipedia/commons/0/0c/Motorhead-03.jpg",
  "metallica": "https://upload.wikimedia.org/wikipedia/commons/8/81/Metallica_March_2024.jpg",
  "ramones": "https://upload.wikimedia.org/wikipedia/commons/f/f8/Ramones_rocket_to_russia_photo.jpg",
  "sex-pistols": "https://upload.wikimedia.org/wikipedia/commons/1/1e/Sex_Pistols_in_Paradiso.jpg",
  "black-flag": "https://upload.wikimedia.org/wikipedia/commons/7/79/Black_Flag_performing_at_the_Electric_Ballroom_Camden_2019_%28cropped%29.jpg",
  "nirvana": "https://upload.wikimedia.org/wikipedia/commons/2/2e/Nirvana_around_1992_%28high_quality%29_%28cropped%29.jpg",
  "stevie-ray-vaughan": "https://upload.wikimedia.org/wikipedia/commons/4/43/Stevie_Ray_Vaughan_Live_1983.jpg",
  // Free / public-domain portraits via Wikimedia's hash-free FilePath endpoint
  // (small thumbnails for avatars). Any that fail to resolve fall back to initials.
  "louis-armstrong": "https://commons.wikimedia.org/wiki/Special:FilePath/Louis_Armstrong_restored.jpg?width=200",
  "duke-ellington": "https://commons.wikimedia.org/wiki/Special:FilePath/Duke_Ellington_-_publicity.JPG?width=200",
  "king-oliver": "https://commons.wikimedia.org/wiki/Special:FilePath/King_Oliver.jpg?width=200",
  "django-reinhardt": "https://commons.wikimedia.org/wiki/Special:FilePath/Django_Reinhardt_%28Gottlieb%29.jpg?width=200",
  "nina-simone": "https://commons.wikimedia.org/wiki/Special:FilePath/Nina_Simone_1965.jpg?width=200",
  "james-brown": "https://commons.wikimedia.org/wiki/Special:FilePath/James_Brown_Live_Hamburg_1973_1702730029.jpg?width=200",
  "michael-jackson": "https://commons.wikimedia.org/wiki/Special:FilePath/Michael_Jackson_1984.jpg?width=200",
  "bob-marley": "https://commons.wikimedia.org/wiki/Special:FilePath/Bob-Marley-in-Concert_Zurich_05-30-80.jpg?width=200",
  "david-bowie": "https://commons.wikimedia.org/wiki/Special:FilePath/David-Bowie_Chicago_2002-08-08_photoby_Adam-Bielawski.jpg?width=200",
  "kraftwerk": "https://commons.wikimedia.org/wiki/Special:FilePath/Kraftwerk_in_Stockholm_2.jpg?width=200",
  "john-cage": "https://commons.wikimedia.org/wiki/Special:FilePath/John_Cage_%281988%29_by_Ralph_Burgess.jpg?width=200",
  "fannie-charles-dillon": "https://commons.wikimedia.org/wiki/Special:FilePath/Fannie_Charles_Dillon_in_1915.jpg?width=200",
};

// Wikipedia article (English) per artist — a reference link shown in the UI.
const wikiTitles = {
  "charley-patton": "Charley Patton", "son-house": "Son House",
  "blind-lemon-jefferson": "Blind Lemon Jefferson", "robert-johnson": "Robert Johnson",
  "lead-belly": "Lead Belly", "sister-rosetta-tharpe": "Sister Rosetta Tharpe",
  "arthur-crudup": "Arthur Crudup", "big-mama-thornton": "Big Mama Thornton",
  "t-bone-walker": "T-Bone Walker", "muddy-waters": "Muddy Waters",
  "howlin-wolf": "Howlin' Wolf", "bb-king": "B.B. King", "chuck-berry": "Chuck Berry",
  "little-richard": "Little Richard", "elvis-presley": "Elvis Presley",
  "buddy-holly": "Buddy Holly", "woody-guthrie": "Woody Guthrie",
  "hank-williams": "Hank Williams", "the-beatles": "The Beatles",
  "the-rolling-stones": "The Rolling Stones", "bob-dylan": "Bob Dylan",
  "jimi-hendrix": "Jimi Hendrix", "cream": "Cream (band)", "the-stooges": "The Stooges",
  "deep-purple": "Deep Purple", "black-sabbath": "Black Sabbath",
  "led-zeppelin": "Led Zeppelin", "motorhead": "Motörhead",
  "diamond-head": "Diamond Head (band)", "metallica": "Metallica", "ramones": "Ramones",
  "sex-pistols": "Sex Pistols", "black-flag": "Black Flag (band)", "pixies": "Pixies",
  "nirvana": "Nirvana (band)", "stevie-ray-vaughan": "Stevie Ray Vaughan",
  "karlheinz-stockhausen": "Karlheinz Stockhausen", "nina-simone": "Nina Simone",
  "the-velvet-underground": "The Velvet Underground", "david-bowie": "David Bowie",
  "brian-eno": "Brian Eno", "kate-bush": "Kate Bush",
  "cabaret-voltaire": "Cabaret Voltaire", "genesis-p-orridge": "Genesis P-Orridge",
  "kraftwerk": "Kraftwerk", "joy-division": "Joy Division", "new-order": "New Order",
  "king-oliver": "King Oliver", "duke-ellington": "Duke Ellington",
  "louis-armstrong": "Louis Armstrong", "django-reinhardt": "Django Reinhardt",
  "jackie-wilson": "Jackie Wilson", "james-brown": "James Brown",
  "curtis-mayfield": "Curtis Mayfield", "marvin-gaye": "Marvin Gaye",
  "michael-jackson": "Michael Jackson", "bob-marley": "Bob Marley",
  "queen": "Queen (band)",
  "john-cage": "John Cage",
  "fannie-charles-dillon": "Fannie Charles Dillon",
};

for (const a of artists) {
  a.image = imageMap[a.slug] || "";
  const t = wikiTitles[a.slug];
  a.wiki = t ? "https://en.wikipedia.org/wiki/" + encodeURIComponent(t.replace(/ /g, "_")) : "";
}

const E = (artist, influenced_by, description, sources) =>
  ({ artist, influenced_by, description, sources });
const S = (type, citation, author = "", year = null, url = "") =>
  ({ type, citation, author, year, url });

export const influences = [
  // Delta blues lineage
  E("son-house", "charley-patton", "Сон Хаус перенял манеру дельта-блюза, играя рядом с Паттоном.",
    [S("encyclopedia", "AllMusic: Son House формировался в окружении Чарли Паттона.", "AllMusic"),
     S("encyclopedia", "Robert Palmer, «Deep Blues»: Сон Хаус играл и учился рядом с Паттоном в дельте.", "Robert Palmer", 1981)]),
  E("robert-johnson", "son-house", "Сон Хаус лично наблюдал за становлением молодого Джонсона и вспоминал об этом.",
    [S("interview", "Сон Хаус неоднократно рассказывал, как Роберт Джонсон учился у местных блюзменов дельты.", "Son House", 1965)]),
  E("robert-johnson", "charley-patton", "Репертуар и приёмы Паттона вошли в язык Джонсона.",
    [S("encyclopedia", "Музыковедческие разборы прослеживают паттоновские мотивы у Джонсона.", "Grove Music"),
     S("documentary", "«The Search for Robert Johnson» (1991): репертуар и приёмы Паттона в игре Джонсона.", "", 1991)]),
  E("arthur-crudup", "son-house", "Крудап впитал традицию дельта-блюза, идущую от Сон Хауса.",
    [S("encyclopedia", "Биографы относят Крудапа к дельта-блюзовой линии Сон Хауса.", "AllMusic"),
     S("encyclopedia", "Grove Music: Крудап продолжал миссисипскую дельта-традицию.", "Grove Music")]),
  E("t-bone-walker", "blind-lemon-jefferson", "Подростком Уокер водил слепого Лемона Джефферсона и учился у него.",
    [S("encyclopedia", "T-Bone Walker мальчиком сопровождал Blind Lemon Jefferson по улицам Далласа.", "AllMusic"),
     S("interview", "T-Bone Walker вспоминал, как водил слепого Лемона Джефферсона и перенимал его игру.", "T-Bone Walker")]),

  // Electric blues
  E("muddy-waters", "son-house", "Мадди Уотерс называл Сон Хауса своим главным учителем.",
    [S("interview", "Muddy Waters: «Son House — вот кто на меня действительно повлиял».", "Muddy Waters", 1971)]),
  E("muddy-waters", "robert-johnson", "Мадди перенял репертуар и слайд-технику Роберта Джонсона.",
    [S("encyclopedia", "Записи Library of Congress фиксируют влияние Джонсона на раннего Уотерса.", "Library of Congress"),
     S("interview", "Muddy Waters рассказывал, что разучивал пластинки Роберта Джонсона по нотке.", "Muddy Waters", 1971)]),
  E("howlin-wolf", "charley-patton", "Чарли Паттон лично учил молодого Хаулин Вульфа игре и подаче.",
    [S("encyclopedia", "Howlin' Wolf учился у Чарли Паттона на плантации Докери.", "AllMusic"),
     S("interview", "Howlin' Wolf вспоминал, что Чарли Паттон показывал ему игру и подачу.", "Howlin' Wolf")]),
  E("bb-king", "t-bone-walker", "Би Би Кинг говорил, что услышав Уокера, понял, каким хочет быть гитаристом.",
    [S("autobiography", "B.B. King, «Blues All Around Me»: услышанный T-Bone Walker определил его выбор.", "B.B. King", 1996)]),
  E("bb-king", "blind-lemon-jefferson", "Записи Блайнд Лемона звучали в доме Кинга с детства.",
    [S("autobiography", "B.B. King вспоминал пластинки Blind Lemon Jefferson как раннее влияние.", "B.B. King", 1996)]),

  // Rock'n'roll
  E("chuck-berry", "muddy-waters", "Именно Мадди Уотерс привёл Чака Берри на лейбл Chess.",
    [S("autobiography", "Chuck Berry, «The Autobiography»: знакомство и влияние Мадди Уотерса.", "Chuck Berry", 1987)]),
  E("chuck-berry", "t-bone-walker", "Сценические дакхвок-движения и гитарные ходы восходят к Уокеру.",
    [S("encyclopedia", "Историки рок-н-ролла прослеживают приёмы Берри к T-Bone Walker.", "Rolling Stone"),
     S("autobiography", "Chuck Berry, «The Autobiography»: восхищение игрой и сценой T-Bone Walker.", "Chuck Berry", 1987)]),
  E("little-richard", "sister-rosetta-tharpe", "Сестра Розетта вывела юного Литла Ричарда на сцену.",
    [S("documentary", "Док. фильм «The Godmother of Rock & Roll»: Тарп пригласила подростка Ричарда петь.", "", 2011),
     S("interview", "Little Richard рассказывал, как выступление с Сестрой Розеттой в 1947 открыло ему сцену.", "Little Richard")]),
  E("elvis-presley", "arthur-crudup", "Дебютный сингл Элвиса — кавер «That's All Right» Артура Крудапа.",
    [S("interview", "Elvis: «Если бы я мог петь как Артур Крудап, я был бы счастлив».", "Elvis Presley", 1956, "https://en.wikipedia.org/wiki/That%27s_All_Right")]),
  E("elvis-presley", "big-mama-thornton", "«Hound Dog» Элвиса — версия песни, впервые записанной Big Mama Thornton.",
    [S("encyclopedia", "Оригинал «Hound Dog» записан Big Mama Thornton в 1952 году.", "AllMusic", 1952, "https://en.wikipedia.org/wiki/Hound_Dog_(song)"),
     S("documentary", "«Elvis Presley: The Searcher» (HBO, 2018): происхождение «Hound Dog» от версии Тортон.", "", 2018)]),
  E("elvis-presley", "sister-rosetta-tharpe", "Госпел-фразировка Тарп слышна в ранней манере Элвиса.",
    [S("documentary", "BBC: влияние Sister Rosetta Tharpe на вокал раннего рок-н-ролла, включая Элвиса.", "BBC"),
     S("encyclopedia", "AllMusic: госпел-фразировка Тарп — часть корней вокала Пресли.", "AllMusic")]),

  // Folk / country to Dylan
  E("bob-dylan", "woody-guthrie", "Дилан приехал в Нью-Йорк, чтобы навестить кумира Вуди Гатри.",
    [S("autobiography", "Bob Dylan, «Chronicles, Vol. 1»: Гатри как определяющее влияние.", "Bob Dylan", 2004, "https://en.wikipedia.org/wiki/Chronicles,_Volume_One")]),
  E("bob-dylan", "robert-johnson", "Дилан подробно описывал, как пластинки Джонсона перевернули его письмо.",
    [S("autobiography", "Bob Dylan, «Chronicles, Vol. 1»: влияние Роберта Джонсона на тексты.", "Bob Dylan", 2004)]),
  E("bob-dylan", "hank-williams", "Дилан называл песни Хэнка Уильямса школой сонграйтинга.",
    [S("autobiography", "Bob Dylan, «Chronicles, Vol. 1»: Хэнк Уильямс как учитель.", "Bob Dylan", 2004)]),

  // British Invasion
  E("the-beatles", "chuck-berry", "Битлз исполняли и записывали песни Чака Берри.",
    [S("interview", "John Lennon: «Если дать рок-н-роллу другое имя, это будет Chuck Berry».", "John Lennon", 1972)]),
  E("the-beatles", "elvis-presley", "Элвис был главным юношеским образцом для участников группы.",
    [S("interview", "John Lennon: «До Элвиса не было ничего».", "John Lennon")]),
  E("the-beatles", "little-richard", "Пол Маккартни перенял крик-вокал у Литла Ричарда.",
    [S("interview", "Paul McCartney рассказывал, что учился вокалу по записям Little Richard.", "Paul McCartney")]),
  E("the-beatles", "buddy-holly", "Само название и формат группы вдохновлены The Crickets Бадди Холли.",
    [S("encyclopedia", "Имя «Beatles» — отсылка к «Crickets»; влияние Buddy Holly на формат группы.", "AllMusic"),
     S("interview", "Paul McCartney называл The Crickets Бадди Холли образцом самодостаточной группы.", "Paul McCartney")]),
  E("the-rolling-stones", "muddy-waters", "Группа взяла название из песни Мадди Уотерса «Rollin' Stone».",
    [S("encyclopedia", "Название The Rolling Stones происходит от песни Мадди Уотерса.", "AllMusic", 1962, "https://en.wikipedia.org/wiki/Rollin%27_Stone_(Muddy_Waters_song)"),
     S("interview", "Keith Richards: чикагский блюз Мадди Уотерса — причина, по которой возникла группа.", "Keith Richards")]),
  E("the-rolling-stones", "chuck-berry", "Ранний репертуар Stones строился на песнях Чака Берри.",
    [S("interview", "Keith Richards многократно называл Chuck Berry главным влиянием на свою игру.", "Keith Richards")]),
  E("the-rolling-stones", "robert-johnson", "Stones записали «Love in Vain» и «Stop Breaking Down» Джонсона.",
    [S("encyclopedia", "Кавер-версии Роберта Джонсона в репертуаре The Rolling Stones.", "AllMusic"),
     S("encyclopedia", "«Love in Vain» (Let It Bleed, 1969) и «Stop Breaking Down» — песни Джонсона у Stones.", "AllMusic", 1969)]),
  E("the-rolling-stones", "howlin-wolf", "Stones настояли на участии Хаулин Вульфа в эфире Shindig!.",
    [S("documentary", "В 1965 Stones вывели Howlin' Wolf на ТВ-шоу Shindig!.", "", 1965),
     S("interview", "Stones называли Howlin' Wolf кумиром и условием своего появления в эфире.", "The Rolling Stones", 1965)]),

  // Hendrix roots
  E("jimi-hendrix", "muddy-waters", "Хендрикс вспоминал, что первый блюз, напугавший его, был у Мадди Уотерса.",
    [S("interview", "Jimi Hendrix: «Первый гитарист, о котором я узнал, был Muddy Waters».", "Jimi Hendrix", 1968)]),
  E("jimi-hendrix", "bb-king", "Хендрикс впитал выразительную блюзовую фразировку Би Би Кинга.",
    [S("encyclopedia", "Биографы отмечают влияние B.B. King на блюзовую сторону Хендрикса.", "Rolling Stone"),
     S("interview", "Hendrix называл B.B. King среди блюзовых гитаристов, которых впитал.", "Jimi Hendrix")]),
  E("jimi-hendrix", "little-richard", "Хендрикс играл в гастрольной группе Литла Ричарда.",
    [S("encyclopedia", "Jimi Hendrix был гитаристом в группе Little Richard в 1964–65.", "AllMusic", 1965),
     S("interview", "Hendrix вспоминал, что школу сцены и шоу прошёл в группе Little Richard.", "Jimi Hendrix")]),
  E("jimi-hendrix", "bob-dylan", "Кавер «All Along the Watchtower» — дань влиянию Дилана.",
    [S("interview", "Hendrix признавал огромное влияние песен Боба Дилана на свой подход к тексту.", "Jimi Hendrix")]),

  // Cream
  E("cream", "robert-johnson", "Cream сделали хитом «Crossroads» Роберта Джонсона.",
    [S("encyclopedia", "Cream популяризировали «Cross Road Blues» Роберта Джонсона.", "AllMusic", 1968, "https://en.wikipedia.org/wiki/Cross_Road_Blues"),
     S("interview", "Eric Clapton называл Роберта Джонсона важнейшим для себя блюзменом.", "Eric Clapton")]),
  E("cream", "muddy-waters", "Чикагский блюз Уотерса — фундамент репертуара Cream.",
    [S("interview", "Eric Clapton называл Мадди Уотерса крёстным отцом всего, что он делает.", "Eric Clapton")]),

  // Hard rock / metal
  E("led-zeppelin", "howlin-wolf", "Zeppelin адаптировали «How Many More Times» из песен Хаулин Вульфа.",
    [S("encyclopedia", "Ряд тем Led Zeppelin восходит к Howlin' Wolf и Willie Dixon.", "AllMusic"),
     S("encyclopedia", "«The Lemon Song» восходит к «Killing Floor» Howlin' Wolf (последующее урегулирование авторства).", "AllMusic")]),
  E("led-zeppelin", "robert-johnson", "«Travelling Riverside Blues» — прямая отсылка к Джонсону.",
    [S("encyclopedia", "Led Zeppelin записали «Travelling Riverside Blues» Роберта Джонсона.", "AllMusic", null, "https://en.wikipedia.org/wiki/Travelling_Riverside_Blues"),
     S("documentary", "«It Might Get Loud» (2008): Jimmy Page показывает пластинки Роберта Джонсона как формирующие.", "", 2008)]),
  E("led-zeppelin", "muddy-waters", "Чикагский электроблюз Уотерса — основа тяжёлого блюз-рока Zeppelin.",
    [S("interview", "Jimmy Page называл Чесс-блюз, включая Мадди Уотерса, ключевым влиянием.", "Jimmy Page")]),
  E("deep-purple", "jimi-hendrix", "Ритчи Блэкмор называл громкость и драйв Хендрикса ориентиром.",
    [S("interview", "Ritchie Blackmore отмечал влияние Хендрикса на тяжесть звучания.", "Ritchie Blackmore")]),
  E("black-sabbath", "cream", "Ранний Sabbath отталкивался от тяжёлого блюз-рока Cream.",
    [S("interview", "Tony Iommi называл Cream одним из первых ориентиров группы.", "Tony Iommi")]),
  E("motorhead", "jimi-hendrix", "Лемми работал роуди у Хендрикса и считал его огромным влиянием.",
    [S("autobiography", "Lemmy, «White Line Fever»: работа с Хендриксом и его влияние.", "Lemmy Kilmister", 2002, "https://en.wikipedia.org/wiki/White_Line_Fever_(book)")]),
  E("motorhead", "little-richard", "Лемми называл рок-н-ролл Литла Ричарда корнем своей энергетики.",
    [S("autobiography", "Lemmy, «White Line Fever»: любовь к рок-н-роллу Little Richard.", "Lemmy Kilmister", 2002)]),
  E("motorhead", "the-beatles", "Лемми видел ранних Beatles живьём и считал их жёсткой рок-группой.",
    [S("interview", "Lemmy многократно говорил, что The Beatles — недооценённо тяжёлая группа.", "Lemmy Kilmister")]),
  E("diamond-head", "black-sabbath", "NWOBHM Diamond Head выросла на риффах Black Sabbath.",
    [S("encyclopedia", "Diamond Head относят к наследникам Black Sabbath и Led Zeppelin.", "AllMusic"),
     S("interview", "Музыканты Diamond Head называли Black Sabbath среди формирующих влияний.", "Diamond Head")]),
  E("diamond-head", "led-zeppelin", "Структуры песен Diamond Head наследуют Led Zeppelin.",
    [S("encyclopedia", "Критики отмечают цеппелиновское влияние на Diamond Head.", "AllMusic"),
     S("documentary", "Ретроспективы NWOBHM: структуры песен Diamond Head наследуют Led Zeppelin.", "")]),
  E("metallica", "motorhead", "Скорость и напор Motörhead — прямой предок трэша Metallica.",
    [S("interview", "Lars Ulrich называл Motörhead одним из главных влияний Metallica.", "Lars Ulrich")]),
  E("metallica", "diamond-head", "Metallica записали несколько каверов Diamond Head.",
    [S("encyclopedia", "Metallica исполняли «Am I Evil?» и др. песни Diamond Head.", "AllMusic", null, "https://en.wikipedia.org/wiki/Am_I_Evil%3F"),
     S("interview", "Lars Ulrich называл Diamond Head любимой группой — отсюда каверы в репертуаре Metallica.", "Lars Ulrich")]),
  E("metallica", "black-sabbath", "Тяжесть Black Sabbath — фундамент звука Metallica.",
    [S("interview", "Участники Metallica называли Black Sabbath основой тяжёлой музыки.", "Metallica")]),
  E("metallica", "deep-purple", "Ранний Ларс Ульрих вдохновлялся напором Deep Purple.",
    [S("interview", "Lars Ulrich вспоминал Deep Purple среди формирующих влияний.", "Lars Ulrich")]),
  E("metallica", "led-zeppelin", "Джеймс Хэтфилд называл Led Zeppelin ключевым ориентиром.",
    [S("interview", "James Hetfield отмечал влияние Led Zeppelin на риффы.", "James Hetfield")]),

  // Punk lineage
  E("ramones", "the-stooges", "Сырой прото-панк Stooges — прямой предок Ramones.",
    [S("encyclopedia", "The Stooges называют ключевым влиянием на Ramones.", "AllMusic"),
     S("interview", "Ramones называли «Raw Power» Stooges формирующим прото-панк-влиянием.", "Ramones")]),
  E("ramones", "the-beatles", "Мелодизм и короткие песни Ramones — наследие Beatles.",
    [S("interview", "Johnny Ramone называл The Beatles причиной взять гитару.", "Johnny Ramone")]),
  E("sex-pistols", "the-stooges", "Иэн и Игги Поп — образец сценического панка для Pistols.",
    [S("encyclopedia", "The Stooges и Iggy Pop — ключевое влияние на Sex Pistols.", "AllMusic"),
     S("documentary", "«The Filth and the Fury» (2000): образ Игги Попа как сценический ориентир Pistols.", "", 2000)]),
  E("sex-pistols", "ramones", "Турне и записи Ramones подтолкнули британскую панк-сцену.",
    [S("documentary", "Док. материалы фиксируют влияние Ramones на лондонский панк 1976.", "", 1976),
     S("encyclopedia", "AllMusic: дебют Ramones (1976) ускорил формирование британской панк-сцены.", "AllMusic", 1976)]),
  E("black-flag", "the-stooges", "Хардкор Black Flag вырос из агрессии Stooges.",
    [S("encyclopedia", "The Stooges — общий предок калифорнийского хардкора, включая Black Flag.", "AllMusic"),
     S("interview", "Музыканты Black Flag называли The Stooges истоком хардкор-энергии.", "Black Flag")]),

  // Grunge
  E("nirvana", "pixies", "Кобейн признавал, что «Smells Like Teen Spirit» — попытка написать песню Pixies.",
    [S("interview", "Kurt Cobain (Rolling Stone, 1994): «Я попросту пытался копировать Pixies».", "Kurt Cobain", 1994, "https://en.wikipedia.org/wiki/Smells_Like_Teen_Spirit")]),
  E("nirvana", "the-stooges", "Альбом «Raw Power» Stooges Кобейн называл любимым.",
    [S("interview", "Kurt Cobain ставил «Raw Power» The Stooges на первое место в списке любимых альбомов.", "Kurt Cobain")]),
  E("nirvana", "black-flag", "Хардкор Black Flag — часть панк-фундамента Nirvana.",
    [S("interview", "Kurt Cobain называл Black Flag среди формирующих панк-влияний.", "Kurt Cobain")]),
  E("nirvana", "black-sabbath", "Тяжёлые риффы Nirvana наследуют Black Sabbath.",
    [S("interview", "Участники Nirvana называли Black Sabbath источником тяжести звука.", "Nirvana")]),
  E("nirvana", "lead-belly", "Финал «Unplugged» — кавер «Where Did You Sleep Last Night» Лед Белли.",
    [S("interview", "Kurt Cobain представил песню как вещь Lead Belly, своего любимого исполнителя.", "Kurt Cobain", 1993, "https://en.wikipedia.org/wiki/Where_Did_You_Sleep_Last_Night")]),
  E("pixies", "the-stooges", "Громко-тихая динамика Pixies восходит к панк-энергии Stooges.",
    [S("encyclopedia", "Влияние The Stooges на альтернативный рок, включая Pixies.", "AllMusic"),
     S("documentary", "Ретроспективы альт-рока: прото-панк Stooges в громко-тихой динамике Pixies.", "")]),

  // Blues revival
  E("stevie-ray-vaughan", "jimi-hendrix", "Воган открыто строил репертуар вокруг каверов Хендрикса.",
    [S("encyclopedia", "Stevie Ray Vaughan исполнял «Voodoo Child» и др. вещи Хендрикса.", "AllMusic"),
     S("interview", "SRV открыто называл Джими Хендрикса главным кумиром и строил репертуар на его вещах.", "Stevie Ray Vaughan")]),
  E("stevie-ray-vaughan", "bb-king", "Блюзовая фразировка Вогана наследует Би Би Кингу.",
    [S("interview", "SRV называл B.B. King в числе главных учителей блюза.", "Stevie Ray Vaughan")]),

  // --- Jazz / New Orleans cluster ---
  E("louis-armstrong", "king-oliver", "Oliver was Armstrong's mentor; Armstrong joined his Creole Jazz Band in Chicago in 1922 and modelled his early style directly on Oliver.",
    [S("autobiography", "Louis Armstrong, 'Satchmo: My Life in New Orleans' (1954): King Oliver was my idol and teacher.", "Louis Armstrong", 1954),
     S("encyclopedia", "AllMusic: King Oliver's Creole Jazz Band was the crucible of Armstrong's early development.", "AllMusic")]),

  E("django-reinhardt", "louis-armstrong", "Armstrong's improvisational freedom and jazz phrasing were foundational for Django; they admired each other and Django absorbed Armstrong's recordings intensely.",
    [S("encyclopedia", "AllMusic: Louis Armstrong's jazz idiom was foundational for Django Reinhardt's improvisational approach.", "AllMusic"),
     S("documentary", "'The Django Legacy': Armstrong's recordings were among the first jazz music Django encountered and studied.", "")]),
  E("django-reinhardt", "duke-ellington", "Django toured the US with Ellington in 1946; Ellington was his primary model for jazz sophistication and composition.",
    [S("autobiography", "Duke Ellington, 'Music Is My Mistress' (1973): praised Django as the greatest guitarist he had ever heard.", "Duke Ellington", 1973),
     S("encyclopedia", "AllMusic: Django Reinhardt's 1946 US tour with Duke Ellington is among the most documented partnerships in jazz history.", "AllMusic", 1946)]),

  // --- Soul / funk / R&B cluster ---
  E("michael-jackson", "james-brown", "Jackson called Brown 'the greatest entertainer who ever lived' and built his entire dance vocabulary and stage approach around him.",
    [S("autobiography", "Michael Jackson, 'Moonwalk' (1988): James Brown was my greatest inspiration and I studied his every move.", "Michael Jackson", 1988),
     S("interview", "Michael Jackson repeatedly cited James Brown in press interviews as his primary performance model.", "Michael Jackson")]),
  E("michael-jackson", "jackie-wilson", "Jackson studied Wilson's footwork and vocal acrobatics from childhood, directly modelling his performance style on him.",
    [S("interview", "Michael Jackson: 'Jackie Wilson was one of my greatest influences — I used to watch him and study every move.'", "Michael Jackson"),
     S("encyclopedia", "AllMusic: Jackie Wilson's stage techniques — spins, footwork, vocal theatrics — were directly absorbed by Michael Jackson.", "AllMusic")]),
  // Natural intersection with existing graph: Little Richard is already in DB
  E("michael-jackson", "little-richard", "Little Richard's uninhibited vocal energy and showmanship were formative influences on the young Jackson.",
    [S("interview", "Michael Jackson cited Little Richard among his earliest musical inspirations in multiple interviews.", "Michael Jackson"),
     S("encyclopedia", "AllMusic: Little Richard's flamboyant style and raw vocal power directly shaped Michael Jackson's early approach.", "AllMusic")]),
  E("michael-jackson", "marvin-gaye", "Gaye's blend of sensual soul and social commentary shaped Jackson's lyrical ambition on albums like 'Off the Wall' and 'Thriller'.",
    [S("interview", "Michael Jackson cited Marvin Gaye as a key influence on his songwriting and ability to communicate social messages.", "Michael Jackson"),
     S("encyclopedia", "AllMusic: Marvin Gaye's Motown sophistication and emotional depth were a direct touchstone for Michael Jackson.", "AllMusic")]),

  E("bob-marley", "curtis-mayfield", "Mayfield's blend of soul, social consciousness and spiritual uplift directly shaped Marley's lyrical vision with The Wailers.",
    [S("interview", "Bob Marley cited Curtis Mayfield as one of the most important influences on his music and his message.", "Bob Marley"),
     S("encyclopedia", "AllMusic: Curtis Mayfield's socially charged soul was a key acknowledged influence on Bob Marley's songwriting.", "AllMusic")]),

  // --- Queen (all four roots are natural intersections with existing graph) ---
  E("queen", "the-beatles", "Freddie Mercury and Brian May cited the Beatles as their primary model for melodic songwriting, studio ambition and vocal harmony.",
    [S("interview", "Freddie Mercury stated the Beatles were the reason he wanted to be in a band and their harmonies were Queen's blueprint.", "Freddie Mercury"),
     S("encyclopedia", "AllMusic: Queen's multi-layered vocal harmonies and ambitious studio craft owe a direct debt to the Beatles.", "AllMusic")]),
  E("queen", "led-zeppelin", "Brian May's guitar orchestration and Queen's heavy arrangements draw directly from Led Zeppelin's dynamic range.",
    [S("interview", "Brian May cited Jimmy Page and Led Zeppelin as the benchmark for hard rock guitar and dramatic arrangement.", "Brian May"),
     S("encyclopedia", "AllMusic: Led Zeppelin's power and dynamic range were a cornerstone influence on Queen's hard rock approach.", "AllMusic")]),
  E("queen", "david-bowie", "Bowie's glam theatricality and persona-driven artistry shaped Queen's visual identity and Freddie Mercury's stage presence.",
    [S("interview", "Freddie Mercury cited David Bowie's theatrical staging as a key influence on Queen's live performance approach.", "Freddie Mercury"),
     S("encyclopedia", "AllMusic: Bowie's glam-rock flamboyance directly influenced Queen's aesthetic and showmanship.", "AllMusic")]),
  E("queen", "jimi-hendrix", "Brian May built his guitar vocabulary around Hendrix's innovations in tone, feedback and expressive range.",
    [S("interview", "Brian May: 'Jimi Hendrix was the single biggest influence on my guitar playing — he changed everything for me.'", "Brian May"),
     S("encyclopedia", "AllMusic: Jimi Hendrix's revolutionary guitar techniques were central to Brian May's style and tone.", "AllMusic")]),

  // --- Krautrock / electronic cluster ---
  E("kraftwerk", "karlheinz-stockhausen", "Ralf Hütter and Florian Schneider studied under Stockhausen at Darmstadt; his tape and electronic methods were their foundation.",
    [S("interview", "Ralf Hütter cited Stockhausen's Darmstadt courses as the starting point for Kraftwerk's electronic approach.", "Ralf Hütter"),
     S("encyclopedia", "AllMusic: Stockhausen's influence on Kraftwerk's electronic and compositional methods is extensively documented.", "AllMusic")]),

  E("david-bowie", "kraftwerk", "Bowie's Berlin Trilogy ('Low', 'Heroes', 'Lodger') was directly triggered by hearing Kraftwerk's 'Autobahn' on tour.",
    [S("interview", "David Bowie stated that hearing Kraftwerk's 'Autobahn' changed the direction of his music and led to the Berlin period.", "David Bowie"),
     S("encyclopedia", "AllMusic: Kraftwerk's influence on Bowie's Berlin Trilogy is one of the most documented episodes in 1970s rock history.", "AllMusic")]),
  E("brian-eno", "kraftwerk", "Eno cited Kraftwerk's systematic approach to timbre and texture as a key influence on his ambient and production work.",
    [S("interview", "Brian Eno named Kraftwerk among the artists who most shaped his approach to electronic music and ambient composition.", "Brian Eno"),
     S("encyclopedia", "AllMusic: Kraftwerk's electronic minimalism was an acknowledged influence on Brian Eno's ambient music development.", "AllMusic")]),
  E("cabaret-voltaire", "kraftwerk", "Cabaret Voltaire cited Kraftwerk's rhythmic machine music as a direct model for their tape-loop and synthesizer experiments.",
    [S("interview", "Cabaret Voltaire members named Kraftwerk among their primary electronic influences in multiple interviews.", "Cabaret Voltaire"),
     S("encyclopedia", "AllMusic: Kraftwerk's influence on Cabaret Voltaire's electronic direction is well documented.", "AllMusic")]),

  // New natural link: Nina Simone ← Duke Ellington (both in DB)
  E("nina-simone", "duke-ellington", "Simone cited Ellington as a major model for combining jazz sophistication with personal expression and orchestral imagination.",
    [S("interview", "Nina Simone named Duke Ellington as one of her most important musical inspirations in interviews.", "Nina Simone"),
     S("encyclopedia", "AllMusic: Duke Ellington's jazz sophistication and compositional ambition directly informed Nina Simone's approach.", "AllMusic")]),

  // --- Post-punk / new wave cluster ---
  E("joy-division", "sex-pistols", "Seeing the Sex Pistols at the Lesser Free Trade Hall on 4 June 1976 directly caused the members to form a band.",
    [S("documentary", "'24 Hour Party People' and multiple documentaries: the Pistols' Lesser Free Trade Hall gig is the founding event of Joy Division.", "", 1976),
     S("encyclopedia", "AllMusic: Joy Division (then Warsaw) formed immediately after witnessing the Sex Pistols in Manchester, June 1976.", "AllMusic", 1976)]),
  E("joy-division", "the-velvet-underground", "Ian Curtis and the band absorbed the Velvet Underground's drone, minimalism and dark lyricism as a core reference.",
    [S("interview", "Ian Curtis and Bernard Sumner both cited The Velvet Underground as a primary influence on Joy Division's atmosphere.", "Ian Curtis"),
     S("encyclopedia", "AllMusic: The Velvet Underground's dark lyricism and minimalist sound were a direct touchstone for Joy Division.", "AllMusic")]),
  E("joy-division", "david-bowie", "Bowie's Berlin Trilogy provided the sonic and emotional blueprint for Joy Division's atmosphere and production approach.",
    [S("interview", "Members of Joy Division cited Bowie's 'Low' and 'Heroes' as crucial influences on the sound and mood of their records.", "Joy Division"),
     S("encyclopedia", "AllMusic: David Bowie's Berlin Trilogy was a defining influence on Joy Division's sound and aesthetic.", "AllMusic")]),
  E("joy-division", "kraftwerk", "Kraftwerk's cold, mechanised rhythms were central to Joy Division's industrial atmosphere and use of drum machines.",
    [S("interview", "Bernard Sumner cited Kraftwerk as a key influence on Joy Division's use of electronic textures and repetitive rhythms.", "Bernard Sumner"),
     S("encyclopedia", "AllMusic: Kraftwerk's electronic influence is clearly audible in Joy Division's sound and production approach.", "AllMusic")]),

  E("new-order", "joy-division", "New Order emerged directly from the surviving members of Joy Division after Ian Curtis's death in 1980.",
    [S("encyclopedia", "AllMusic: New Order formed from Joy Division's remaining members (Bernard Sumner, Peter Hook, Stephen Morris) in 1980.", "AllMusic", 1980),
     S("documentary", "'New Order Story' (1993): the band documents how Joy Division became New Order and carried its legacy forward.", "", 1993)]),
  E("new-order", "kraftwerk", "New Order's turn to electronic dance music was explicitly driven by their admiration for Kraftwerk's rhythmic precision.",
    [S("interview", "Peter Hook and Bernard Sumner cited Kraftwerk as the primary reason New Order embraced synthesizers and drum machines.", "Peter Hook"),
     S("encyclopedia", "AllMusic: Kraftwerk's machine rhythms were the direct catalyst for New Order's electronic direction after Joy Division.", "AllMusic")]),

  // --- Avant-garde / art-rock / electronic / industrial cluster ---
  // John Cage cluster
  E("john-cage", "fannie-charles-dillon", "Dillon was Cage's music teacher at Los Angeles High School in the late 1920s; her practice of transcribing bird calls into scores planted the seed for Cage's lifelong interest in incorporating natural and environmental sounds into music.",
    [S("encyclopedia", "Wikipedia / UCLA Library: Fannie Charles Dillon taught at LA High School in the late 1920s and John Cage was among her students.", "Wikipedia", null, "https://en.wikipedia.org/wiki/Fannie_Charles_Dillon"),
     S("encyclopedia", "David Patterson, 'The Picture That Is Not in the Colors': Cage's early music education in Los Angeles is documented, including study with Dillon before his work with Cowell and Schoenberg.", "Grove Music")]),

  E("karlheinz-stockhausen", "john-cage", "Cage's Darmstadt lectures and aleatoric methods directly triggered Stockhausen's use of chance in 'Klavierstück XI' and subsequent works.",
    [S("encyclopedia", "Grove Music: Cage's 1958 Darmstadt lectures were a pivotal encounter for Stockhausen and redirected his approach to indeterminacy.", "Grove Music", 1958),
     S("interview", "Stockhausen acknowledged Cage's aleatoric ideas as a key catalyst for his own compositional experiments with chance operations.", "Karlheinz Stockhausen")]),

  E("brian-eno", "john-cage", "Cage's concept of music-as-process and his embrace of silence and chance were the philosophical backbone of Eno's ambient and generative music.",
    [S("interview", "Brian Eno: 'Cage taught me that the composer doesn't have to control everything — that the environment and chance are part of the work.'", "Brian Eno"),
     S("encyclopedia", "AllMusic: Cage's process-oriented thinking and ideas about silence were central acknowledged influences on Brian Eno's ambient philosophy.", "AllMusic")]),

  E("the-velvet-underground", "john-cage", "John Cale entered the Velvet Underground from La Monte Young's Theatre of Eternal Music, a group directly built on Cage's drone and noise aesthetics.",
    [S("encyclopedia", "AllMusic: John Cale's background in Cage-influenced minimalism via La Monte Young brought experimental noise and drone into the Velvet Underground.", "AllMusic"),
     S("encyclopedia", "Grove Music: La Monte Young's Theatre of Eternal Music — the immediate precursor to Cale's work with the VU — grew directly out of Cagean ideas.", "Grove Music")]),

  E("cabaret-voltaire", "john-cage", "Cabaret Voltaire's embrace of noise as music and tape collage as composition drew explicitly on Cage's expanded definition of sound.",
    [S("interview", "Cabaret Voltaire members cited Cage's 4'33\" and his noise aesthetics as foundational to their approach to industrial sound.", "Cabaret Voltaire"),
     S("encyclopedia", "AllMusic: Cage's noise philosophy and tape-music ideas are a documented root of Cabaret Voltaire's experimental direction.", "AllMusic")]),

  E("genesis-p-orridge", "john-cage", "P-Orridge cited Cage's redefinition of music and performance art as a primary philosophical model for Throbbing Gristle's industrial practice.",
    [S("interview", "Genesis P-Orridge explicitly cited John Cage's challenge to the definition of music as a foundational influence on Throbbing Gristle.", "Genesis P-Orridge"),
     S("documentary", "Documentary interviews with P-Orridge repeatedly reference Cage's ideas about sound, noise and performance as central to the industrial music concept.", "")]),

  // Bridge into the existing graph: Stockhausen's tape/musique-concrète методы — у Beatles.
  E("the-beatles", "karlheinz-stockhausen", "Студийные эксперименты Beatles («Revolution 9», лупы) восходят к Штокхаузену; он — на обложке «Sgt. Pepper».",
    [S("interview", "Paul McCartney рассказывал об интересе к Штокхаузену и tape-музыке в период «Revolution 9».", "Paul McCartney"),
     S("encyclopedia", "Karlheinz Stockhausen помещён на обложку «Sgt. Pepper's Lonely Hearts Club Band» (1967) как влияние.", "AllMusic", 1967)]),

  E("brian-eno", "karlheinz-stockhausen", "Эно отталкивался от электронной и процессуальной музыки Штокхаузена.",
    [S("interview", "Brian Eno называл Штокхаузена среди формирующих авангардных влияний.", "Brian Eno"),
     S("encyclopedia", "AllMusic: ранний Эно опирался на электронную традицию Штокхаузена и Кейджа.", "AllMusic")]),
  E("brian-eno", "the-velvet-underground", "Эно называл первый альбом Velvet Underground определяющим для себя.",
    [S("interview", "Brian Eno (часто цитируемое): дебют VU купили немногие, но каждый создал группу.", "Brian Eno"),
     S("encyclopedia", "AllMusic: авангардный рок VU — ключевой ориентир арт-рока, включая Эно.", "AllMusic")]),

  E("david-bowie", "the-velvet-underground", "Боуи боготворил Velvet Underground и исполнял «I'm Waiting for the Man» с ранних лет.",
    [S("interview", "David Bowie многократно называл Лу Рида и VU важнейшим ранним влиянием.", "David Bowie"),
     S("encyclopedia", "AllMusic: влияние The Velvet Underground на Дэвида Боуи.", "AllMusic")]),
  E("david-bowie", "nina-simone", "Версию «Wild Is the Wind» Боуи записал под впечатлением от трактовки Нины Симон.",
    [S("documentary", "Биографические материалы: Боуи восхищался Ниной Симон, отсюда его «Wild Is the Wind» (1976).", "", 1976),
     S("encyclopedia", "AllMusic: «Wild Is the Wind» Боуи отсылает к интерпретации Нины Симон.", "AllMusic")]),

  E("kate-bush", "david-bowie", "Театральность образа и арт-рок Боуи — ориентир для ранней Кейт Буш.",
    [S("interview", "Kate Bush называла Дэвида Боуи в числе вдохновивших её артистов.", "Kate Bush"),
     S("encyclopedia", "AllMusic: арт-рок и образность Боуи в формировании стиля Кейт Буш.", "AllMusic")]),

  E("cabaret-voltaire", "karlheinz-stockhausen", "Электронные методы и шумовая эстетика Cabaret Voltaire идут от авангарда Штокхаузена.",
    [S("interview", "Участники Cabaret Voltaire называли Штокхаузена и tape-музыку основой подхода.", "Cabaret Voltaire"),
     S("encyclopedia", "AllMusic: индустриальная электроника Cabaret Voltaire опирается на авангард Штокхаузена.", "AllMusic")]),
  E("cabaret-voltaire", "brian-eno", "Студийные и плёночные приёмы раннего Эно — ориентир для Cabaret Voltaire.",
    [S("encyclopedia", "AllMusic: ранний эмбиент и обработка Эно среди влияний Cabaret Voltaire.", "AllMusic"),
     S("documentary", "Материалы о шеффилдской сцене: tape-эксперименты Эно как опора Cabaret Voltaire.", "")]),
  E("cabaret-voltaire", "the-velvet-underground", "Авангардный рок и нойз VU — часть ДНК Cabaret Voltaire.",
    [S("encyclopedia", "AllMusic: влияние The Velvet Underground на ранний индастриал, включая Cabaret Voltaire.", "AllMusic"),
     S("documentary", "Ретроспективы индастриала: VU как общий предок шеффилдской электроники.", "")]),

  E("genesis-p-orridge", "the-velvet-underground", "П-Орридж называл Velvet Underground и Лу Рида формирующим влиянием.",
    [S("interview", "Genesis P-Orridge называл VU среди важнейших для себя источников.", "Genesis P-Orridge"),
     S("encyclopedia", "AllMusic: авангардный рок VU — корень индустриальной сцены П-Орриджа.", "AllMusic")]),
  E("genesis-p-orridge", "brian-eno", "Идеи нерепетируемого звука и tape-обработки Эно повлияли на индустриальный метод П-Орриджа.",
    [S("encyclopedia", "AllMusic: студийные идеи Эно среди влияний на Throbbing Gristle и П-Орриджа.", "AllMusic"),
     S("documentary", "Материалы об индастриале: процессуальный подход Эно как ориентир П-Орриджа.", "")]),
];
